### ISSUE TITLE
Submitting a task to a specific worker

### ISSUE THREAD

**Issue by kishaningithub** [gammazero/workerpool#16]
A concurrent put to a same dynamodb resource fails in [aws-sdk-go](https://github.com/aws/aws-sdk-go) so i was thinking if i could redirect put calls to specific workers (1 worker for each table and there can be a lot of tables) i would be able to solve this problem

**Comment by kishaningithub** [comment]
Linking with [aws-sdk-go issue](https://github.com/aws/aws-sdk-go/issues/2623)

**Comment by gammazero** [comment]
@kishaningithub Workerpool is specifically concerned with limiting concurrency.  What you are looking for is a scheduler to execute tasks having the same key (hash, table name, etc.) serially, and execute tasks with different keys concurrently.  Such a scheduler can use a `Workerpool` if limiting concurrency is also a goal, or can simply use a goroutine per key/queue if concurrency limiting is not needed.

The point is that these are two separate problems: 1. concurrency limiting 2. serial/concurrent scheduling. Workerpool only addresses 1.

The scheduling issue you are want to address is not an uncommon pattern, and I can see how it would be nice to use a `Workerpool` in combination.  I would prefer to provide an implementation as a separate package, since it is a separate problem domain.  Here is my basic idea:

Create a `KeyedScheduler` (name TBD) providing it an optional `Workerpool`. Tasks are submitted to the scheduler along with a task key.  The task is put on a queue specific to that key.  Tasks on the same queue (with same key) are executed serially with regard to other tasks on that queue. Tasks from different queues are executed concurrently.  If a `Workerpool` was provided, tasks are submitted to the worker pool for execution.  Otherwise, tasks are executed by a goroutine for each queue.

Does that sound like what you are looking for?

**Comment by kishaningithub** [comment]
Yes! Totally agree!! It so turns out the problem i faced was because of a minor bug in my [dynamodb-backup-restore](https://github.com/kishaningithub/dynamodb-backup-restore) CLI utility. The `KeyedScheduler` is very interesting and would definitely like to work with you on this!! If you have a wiki where you list users of worker pool, I would definitely like to put my CLI there!!

**Comment by gammazero** [comment]
If you would like to put your CLI in a wiki page, you should be able to edit this: https://github.com/gammazero/workerpool/wiki

As far as the `KeyedScheduler` is concerned, that should be a totally separate project, not a subproject of workerpool.  This is because it can apply to a much broader set of workflow issues, that are far outside the scope of workerpool.

**Comment by gammazero** [comment]
Closing that as "not an issue with workerpool".  The requested functionality should be built separately.
