### ISSUE TITLE
How to monitor progression on pool?

### ISSUE THREAD

**Issue by sonhnguyenn** [gammazero/workerpool#28]
How do I say tracking progress on which job is done and % of done job overall? Like displaying completed, queued, waiting to be queued jobs.

**Comment by gammazero** [comment]
Workerpool can tell you how many tasks are queued by calling [WaitingQueueSize](https://godoc.org/github.com/gammazero/workerpool#WorkerPool.WaitingQueueSize).  If that number is greater than zero, then you also know that the number of running tasks is equal to the pool size, since tasks are queued only after all workers are in use.

Other than that, tracking your job metrics is left up to your application.  Workerpool does not track when a job is completed, only when workers are available. It does not track how many tasks have been started.  I feel that keeping these stats is best left to the application if such tracking is necessary.

**Comment by gammazero** [comment]
The reason that your app should keep these stats is because Workerpool could only guess at what you want to record.  Maybe you want to record the number of currently queued/running functions, total queued time, total running time, queued/running duration for individual functions, etc.

A way to track these stats would be to create a wrapper function that adjusts counters before and after calling the wrapped function.  Then submit the wrapper function, that wraps the real function, to Workerpool.
