### ISSUE TITLE
How to avoid task queueing (handling priority)

### ISSUE THREAD

**Issue by radeksimko** [gammazero/workerpool#43]
In a use case I'd like to use this workerpool for I have a need for a more granular control over the queue (e.g. set priorities for tasks, which may also repeatedly change while the task in waiting in the queue).

I can implement the queueing logic myself, outside of this library, but I don't see how I could prevent the library from queueing the tasks within itself.

The only way there seems to be is by checking whether the queue is not empty and prevent submitting new tasks, e.g.

```
if wp.WaitingQueueSize() > 0 {
  // custom queue logic
} else {
  wp.Submit(task)
}
```

That would however still result in potentially 1 task stuck in the WP queue, which may change priority until it is actually executed and therefore delay execution of higher priority tasks.

Would there be interest in adding a method to check the number of active workers?

**Comment by gammazero** [comment]
The priority queues I have generally seen use separate channels for different priorities, all feeding the same pool of goroutines.  The highest priority channel is serviced until empty before servicing the next lower priority channel, and so on... I assume you doing something similar and feeding tasks to this worker pool.

The problem is that this workerpool is designed to be a non-blocking pool that you throw as many tasks at as you like without ever having to wait, even if that task is not immediately runnable.  What you probably need is a blocking workerpool.  So that when there are no available workers, the pool will not accept another task, and your tasks will stack up in the appropriate queues or channels.

To respond to your suggestion above, I do not think checking the number of active workers will be very reliable as that may become completely different immediately after the check.  If that is still needed, then have the functions that are called increment and decrement a counter on entry and exit (or create a generic wrapper that does that).

A blocking implementation would be much simpler since most of the complexity in this workerpool arises from needing to handle queuing tasks when all workers are busy.

**Comment by radeksimko** [comment]
That is fair. I did eventually implement a custom worker pool with priority handling https://github.com/hashicorp/terraform-ls/blob/main/internal/terraform/module/module_loader.go

So with that in mind I'm going to close this issue.
